#!/usr/bin/env python3

import requests
import hmac
import hashlib
import sys
import time
import yaml
from os.path import expanduser

try:
    with open(expanduser("~") + "/.antpoolmon.conf", "r") as cfile:
        cnf = yaml.load(cfile, yaml.BaseLoader)
        username = cnf['username']
        key = cnf['key']
        secret = cnf['secret']

    nonce = int(time.time()*1000)
    message = username + key + str(nonce)
    signature = hmac.new(
        secret.encode('utf-8'),
        msg=message.encode('utf-8'),
        digestmod=hashlib.sha256,
    ).hexdigest().upper()

    req = requests.post(
        'https://antpool.com/api/poolStats.htm',
        data={
            'key': key,
            'nonce': nonce,
            'signature': signature,
            'coin': 'BTC',
        }
    )

    resp = req.json()

    b_minutes, b_seconds = divmod(int(resp['data']['estimateTime']), 60)
    b_hours, b_minutes = divmod(b_minutes, 60)

    r_minutes, r_seconds = divmod(int(resp['data']['currentRound']), 60)
    r_hours, r_minutes = divmod(r_minutes, 60)

    print("\nPool Status       : {}".format(resp['data']['poolStatus']))
    print(
        "Pool Hashrate     : {:.2f} Ph/s".format(
            float(resp['data']['poolHashrate']) / 1000000000))
    print(
        "Network Difficulty: {:,}".format(float(resp['data']['networkDiff'])))
    print(
        "Active Workers    : {:,}".format(
            int(resp['data']['activeWorkerNumber'])))
    print("Block Estimate    : {}:{}:{}".format(b_hours, b_minutes, b_seconds))
    print("Current Round     : {}:{}:{}".format(r_hours, r_minutes, r_seconds))
    print(
        "Total Shares      : {:,}".format(
            int(resp['data']['totalShareNumber'])))
    print(
        "Total Blocks      : {:,}\n\n".format(
            int(resp['data']['totalBlockNumber'])))

    """ Get account details """

    req = requests.post(
        "https://antpool.com/api/account.htm",
        data={'key': key, 'nonce': str(nonce), 'signature': signature})
    acc = req.json()

    print("Earnings:")

    print("24 Hrs: {:<14} Total: {:<14} Paid Out: {:<14} Balance: {}".format(
            acc['data']['earn24Hours'],
            acc['data']['earnTotal'],
            acc['data']['paidOut'],
            acc['data']['balance']))

    """ Get hashrate by workers """

    print("\n\n{0:20} {1:>9} {2:>9} {3:>9} ".format(
        "Workers", "Last 10M", "Last 30M", "Last 1H"), end="")
    print("{0:>9} {1:>9} {2:>9} {3:>9} {4:>9}".format(
        "Last 1D", "Accepted", "Stale", "Duplicate", "Other"))
    print("-" * 100)

    workers = requests.post(
        "https://antpool.com/api/workers.htm",
        data={'key': key, 'nonce': str(nonce), 'signature': signature}).json()

    for w in workers['data']['rows']:
        print("{0:20} {1:>9.2f} {2:>9.2f} {3:>9.2f} {4:>9.2f}".format(
            w['worker'],
            float(w['last10m']) / 1000,
            float(w['last30m']) / 1000,
            float(w['last1h']) / 1000,
            float(w['last1d']) / 1000,
            ), end="")

        print(" {0:>9} {1:>9} {2:>9} {3:>9}".format(
            w['accepted'],
            w['stale'],
            w['dupelicate'],
            w['other']))

    """ Get total hashrate """

    hrate = requests.post(
        "https://antpool.com/api/hashrate.htm",
        data={'key': key, 'nonce': str(nonce), 'signature': signature}).json()

    print("{}{}".format(" " * 23, "-" * 77))

    print("{0:>30.2f} {1:>9.2f} {2:>9.2f} {3:>9.2f}".format(
        float(hrate['data']['last10m']) / 1000,
        float(hrate['data']['last30m']) / 1000,
        float(hrate['data']['last1h']) / 1000,
        float(hrate['data']['last1d']) / 1000,
        ), end="")

    print(" {0:>9} {1:>9} {2:>9} {3:>9}".format(
        hrate['data']['accepted'],
        hrate['data']['stale'],
        hrate['data']['dupelicate'],
        hrate['data']['other']))

    """ Get PPLNS details """

    print("\n\n{0:19} {1:>15} {2:>15} {3:>15} {4:>15}".format(
        "Timestamp", "Height", "diff1 Sh. Cnt", "Type", "Amount"))
    print("-" * 83)

    pplns = requests.post(
        "https://antpool.com/api/paymentHistory.htm",
        data={
            'key': key,
            'nonce': str(nonce),
            'signature': signature,
            'type': 'pplns',
            'pageEnable': 1,
            'page': 1,
            'pageSize': 5
            }
        ).json()

    for p in pplns['data']['rows']:
        print("{0:19} {1:>15,} {2:>15,} {3:>15} {4:>15}".format(
            p['timestamp'],
            int(p['blockHeight']),
            int(p['diff1ShareCount']),
            p['type'],
            p['amount']))

    print()


except OSError as ex:
    print("Error: {}".format(ex), file=sys.stderr)
    sys.exit(1)

except yaml.YAMLError:
    print("Please make sure the file .antpoolmon.conf exists in your home ")
    print("directory and contains the following the following:")
    print('username: "<username>"\nkey: "<key>"\nsecret: "<secret>"\n')
    sys.exit(2)
